version: 2.1

jobs:
  build-capstone:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - restore_cache:
          keys: [fastapi-build]
      - run:
          name: Setup env
          command: |                    
            make setup
      - run:
          name: Install requirements
          command: |          
            ls -l
            make install
      - run:
          name: Run lint
          command: |          
           make lint
      - run:
          name: Run tests
          command: |          
           make test
workflows:
  default:
      jobs:
        - build-capstone:
            filters:
                  branches: 
                    only: main